[build]
  publish = "public"
  functions = "netlify/functions"

[[redirects]]
  from = "/"
  to = "/.netlify/functions/renderIndex"
  status = 200
  
[[redirects]]
  from = "/search/update"
  to = "/.netlify/functions/getUpdateRecord"
  status = 200

[[redirects]]
  from = "/search/:cemetery"
  to = "/.netlify/functions/renderSearch"
  status = 200
  force = true

[functions]
  included_files = ["public/views/**"]
